bajastecnicas/bajas/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'bajas'

urlpatterns = [
    path('', views.bajas_list, name="list"), 
    path('<int:id>', views.bajas_page, name="baja-page"), 
    path('crear-baja/', views.crear_baja, name="crear-baja"),
    path('crear-anexo2/', views.crear_anexo2, name="crear-anexo2"),
    path('crear-anexo3/', views.crear_anexo3, name="crear-anexo3"),
    path('<int:id>/eliminar', views.eliminar_baja, name='eliminar_baja'),
    path('<int:id>/editar', views.editar_baja, name='editar_baja'),                                 
    # path('<int:id>/exportar', views.exportar_pdf, name='exportar_pdf'), 
    path('<int:id>/subir_anexo/', views.subir_anexo_firmado, name='subir_anexo'),

    path('<int:id>/aprobar_anexoA/', views.aprobar_anexoA, name='aprobar_anexoA'),
    path('<int:id>/aprobar_anexoA1/', views.aprobar_anexoA1, name='aprobar_anexoA1'),
    path('<int:id>/aprobar_anexoA2/', views.aprobar_anexoA2, name='aprobar_anexoA2'),
    path('<int:id>/aprobar_anexoA3/', views.aprobar_anexoA3, name='aprobar_anexoA3'),
    
    # Para editar los datos del Anexo A
    
    
    # Ruta para el nuevo botón de crear el PDF del Anexo A (solo después de llenar los datos)
    path('<int:id>/crear_anexoA/', views.crear_anexoA, name='crear_anexoA'),
    path('<int:id>/crear_anexoA1/', views.crear_anexoA1, name='crear_anexoA1'),
    path('<int:id>/crear_anexoA2/', views.crear_anexoA2, name='crear_anexoA2'),
    path('<int:id>/crear_anexoA3/', views.crear_anexoA3, name='crear_anexoA3'),

    # Rutas para las versiones Anexo A1, A2, A3 si existen
    path('<int:id>/trabajar_anexoA/', views.trabajar_anexoA, name='trabajar_anexoA'),
    path('<int:id>/trabajar_anexoA1/', views.trabajar_anexoA1, name='trabajar_anexoA1'),
    path('<int:id>/trabajar_anexoA2/', views.trabajar_anexoA2, name='trabajar_anexoA2'),
    path('<int:id>/trabajar_anexoA3/', views.trabajar_anexoA3, name='trabajar_anexoA3'),

    path('cargar_excel_inv/', views.cargar_excel_inv, name='cargar_excel_inv'),    
    # Ruta para buscar inventarios
    path('buscar_inventario/', views.buscar_inventario, name='buscar_inventario'),  
    path('descargar_anexos/<int:id>/', views.descargar_anexos_zip, name='descargar_anexos'),                        
]

# Para servir archivos estáticos y de medios si estamos en modo DEBUG
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bajastecnicas/bajastecnicas/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('bajas/', include('bajas.urls')),
    path('users/', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bajastecnicas/bajas/views.py
from io import BytesIO
import zipfile
from .decorators import solo_admin_roles
import datetime
from django.http import HttpResponse

from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.db import models
from django.db.models import Q
from datetime import datetime
from .models import Bajas
from .forms import BajasForm
from django.core.paginator import Paginator
import os
from django.conf import settings

from xhtml2pdf import pisa
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
import base64
from django.core.files.storage import default_storage
from .choices import ESTADO_CHOICES
import openpyxl
from django.http import JsonResponse
import pandas as pd
from django.http import JsonResponse
from datetime import datetime
from django.templatetags.static import static
from django.contrib import messages
import os
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.


@login_required
def bajas_list(request):
    puede_admin_roles = request.user.is_superuser or request.user.has_perm(
        "users.administrador_roles")
    bajass = Bajas.objects.all()

    noinv_herramienta = request.GET.get('noinv')
    fecha_inicio = request.GET.get('fecha_inicio')
    fecha_fin = request.GET.get('fecha_fin')
    estado = request.GET.get('estado')
    motivo_baja = request.GET.get('motivo_baja')
    destino_final = request.GET.get('destino_final')
    fecha_inicio_solic = request.GET.get('fecha_inicio_solic')
    fecha_fin_solic = request.GET.get('fecha_fin_solic')
    unidad_org = request.GET.get('unidad_org')
    anexo_a = request.GET.get('anexo_a')
    anexo_a1 = request.GET.get('anexo_a1')
    anexo_a2 = request.GET.get('anexo_a2')
    anexo_a3 = request.GET.get('anexo_a3')
    rechazada = request.GET.get('rechazada')
    terminada = request.GET.get('terminada')

    # Filtro por responsable (ID de usuario)
    responsable_id = request.GET.get('responsable')
    if responsable_id:
        bajass = bajass.filter(responsable_id=responsable_id)

    # Obtener solo los usuarios que ya están asignados como responsables en alguna baja
    responsables_ids = Bajas.objects.exclude(
        responsable__isnull=True).values_list('responsable', flat=True).distinct()
    responsables = User.objects.filter(id__in=responsables_ids)
    # responsables = User.objects.filter(id__in=responsables_ids).order_by('first_name', 'last_name', 'username')

    #filtros para mostrar solo los que van a anexo 2
    rechazada_str = request.GET.get('rechazada')
    listopara_anexo_A2_str = request.GET.get('listopara_anexo_A2')
    listopara_anexo_A3_str = request.GET.get('listopara_anexo_A3')

    # Convertir cadenas a booleanos para los filtros específicos
    if rechazada_str is not None:
        # 'True' se convierte a True, 'False' se convierte a False
        rechazada = rechazada_str.lower() == 'true'
        bajass = bajass.filter(rechazada=rechazada)

    if listopara_anexo_A2_str is not None:
        listopara_anexo_A2 = listopara_anexo_A2_str.lower() == 'true'
        bajass = bajass.filter(listopara_anexo_A2=listopara_anexo_A2)

    if listopara_anexo_A3_str is not None:
        listopara_anexo_A3 = listopara_anexo_A3_str.lower() == 'true'
        bajass = bajass.filter(listopara_anexo_A3=listopara_anexo_A3)
    #fin de filtros para mostrar los que van a anexo 2
    
    if noinv_herramienta:

        # bajas = bajas.filter(no_inv=noinv_herramienta)
        bajass = bajass.filter(models.Q(no_inv=noinv_herramienta) | models.Q(
            inm_herramienta=noinv_herramienta))

    if fecha_inicio:
        bajass = bajass.filter(
            date__gte=datetime.strptime(fecha_inicio, '%Y-%m-%d'))

    if fecha_fin:
        bajass = bajass.filter(
            date__lte=datetime.strptime(fecha_fin, '%Y-%m-%d'))

    if fecha_inicio_solic:
        try:
            bajass = bajass.filter(fecha_solicitud__gte=datetime.strptime(
                fecha_inicio_solic, '%Y-%m-%d'))
        except ValueError:
            pass  # Si la fecha no es válida, no aplicar el filtro

    if fecha_fin_solic:
        try:
            bajass = bajass.filter(
                fecha_solicitud__lte=datetime.strptime(fecha_fin_solic, '%Y-%m-%d'))
        except ValueError:
            pass  # Si la fecha no es válida, no aplicar el filtro

    if estado:
        bajass = bajass.filter(estado=estado)

    if terminada:
        bajass = bajass.filter(terminada=terminada)

    if rechazada:
        bajass = bajass.filter(rechazada=rechazada)

    if unidad_org:
        bajass = bajass.filter(unidad_org=unidad_org)

    if motivo_baja:
        bajass = bajass.filter(motivo_baja=motivo_baja)

    if destino_final:
        bajass = bajass.filter(destino_final=destino_final)

    if anexo_a:
        if anexo_a == 'si':
            bajass = bajass.filter(
                Q(archivo_anexo_a__isnull=False) & ~Q(archivo_anexo_a=''))
        elif anexo_a == 'no':
            bajass = bajass.filter(
                Q(archivo_anexo_a__isnull=True) | Q(archivo_anexo_a=''))

    if anexo_a1:
        if anexo_a1 == 'si':
            bajass = bajass.filter(
                Q(archivo_anexo_a1__isnull=False) & ~Q(archivo_anexo_a1=''))
        elif anexo_a1 == 'no':
            bajass = bajass.filter(
                Q(archivo_anexo_a1__isnull=True) | Q(archivo_anexo_a1=''))

    if anexo_a2:
        if anexo_a2 == 'si':
            bajass = bajass.filter(
                Q(archivo_anexo_a2__isnull=False) & ~Q(archivo_anexo_a2=''))
        elif anexo_a2 == 'no':
            bajass = bajass.filter(
                Q(archivo_anexo_a2__isnull=True) | Q(archivo_anexo_a2=''))
    if anexo_a3:
        if anexo_a3 == 'si':
            bajass = bajass.filter(
                Q(archivo_anexo_a3__isnull=False) & ~Q(archivo_anexo_a3=''))
        elif anexo_a3 == 'no':
            bajass = bajass.filter(
                Q(archivo_anexo_a3__isnull=True) | Q(archivo_anexo_a3=''))
    # if anexo_a2:  # Si anexo_a2 tiene un valor
    #     bajass = bajass.filter(anexo_a2=anexo_a2)

    # if anexo_a3:
    #     bajass = bajass.filter(anexo_a3=anexo_a3)

    bajass = bajass.order_by('id')
    # AQUI EL PAGINADOR COUNT, VOY A PROBAR CON 10
    paginator = Paginator(bajass, 3)
    page_number = request.GET.get('page')
    bajas = paginator.get_page(page_number)

    context = {
        "bajas": bajas,
        "puede_aprobar_anexo_a": request.user.has_perm("users.aprobar_anexo_a"),
        "puede_llenar_anexo_a": request.user.has_perm("users.llenar_anexo_a"),
        "puede_crear_anexo_a": request.user.has_perm("users.crear_anexo_a"),

        "puede_aprobar_anexo_a1": request.user.has_perm("users.aprobar_anexo_a1"),
        "puede_llenar_anexo_a1": request.user.has_perm("users.llenar_anexo_a1"),
        "puede_crear_anexo_a1": request.user.has_perm("users.crear_anexo_a1"),

        "puede_aprobar_anexo_a2": request.user.has_perm("users.aprobar_anexo_a2"),
        "puede_llenar_anexo_a2": request.user.has_perm("users.llenar_anexo_a2"),
        "puede_crear_anexo_a2": request.user.has_perm("users.crear_anexo_a2"),

        "puede_aprobar_anexo_a3": request.user.has_perm("users.aprobar_anexo_a3"),
        "puede_llenar_anexo_a3": request.user.has_perm("users.llenar_anexo_a3"),
        "puede_crear_anexo_a3": request.user.has_perm("users.crear_anexo_a3"),
        "puede_admin_roles": puede_admin_roles,
        # para tener la lista de usuarios que son responsables YA EN ALGUNA BAJA y pasarlo en los filtros
        "responsables": responsables,
    }

    # fin paginador

    return render(request, 'bajas/bajas_list.html', context)


def bajas_page(request, id):
    # return HttpResponse(slug)
    baja = get_object_or_404(Bajas, id=id)
    return render(request, 'bajas/bajas_page.html', {'baja': baja})


def crear_baja(request):
    if request.method == 'POST':
        # Asegúrate de incluir request.FILES para manejar imágenes
        # 👈 paso user aqui para poder manejar lo de solo ciertos usuarios editar responsable, pq pregunto siempre si eres cierto role
        form = BajasForm(request.POST, request.FILES, user=request.user)

        # Si el formulario es válido
        if form.is_valid():
            # Guardar la baja en la base de datos
            baja = form.save()

            # Generar el PDF automáticamente
            context = {'baja': baja,
                       'usuario': request.user,
                       "logo_etecsa": request.build_absolute_uri(static('bajastecnicas/icons/etecsa_logo.jpeg'))}
            html_string = render_to_string('bajas/anexo_a.html', context)
            html_string_a0 = render_to_string('bajas/anexo_0.html', context)

            pdf_path_0 = f'anexos/anexo_{baja.id}_A0.pdf'

            with default_storage.open(pdf_path_0, 'wb') as pdf_file:
                pisa_status = pisa.CreatePDF(html_string_a0, dest=pdf_file)
                if pisa_status.err:
                    return render(request, 'bajas/error.html', {'mensaje': 'Error al generar el PDF a0'})
            baja.archivo_anexo_0 = pdf_path_0
            baja.listopara_anexo_A1 = True
            baja.save()
            return redirect('bajas:list')
    else:
        form = BajasForm(user=request.user)

    # Cargar el archivo Excel para autocompletar los campos
    excel_path = os.path.join(settings.MEDIA_ROOT, 'uploaded/inventario.xlsx')

    try:
        # Leer el archivo Excel
        df = pd.read_excel(excel_path)

        # Limpiar los nombres de las columnas para eliminar posibles espacios
        df.columns = df.columns.str.strip()

        # Acceder a la lista de 'No_inventario' usando su columna C (índice 2)
        no_inv_list = df.iloc[:, 5].drop_duplicates().head(
            5).tolist()  # Columna C (índice 2)

    except Exception as e:

bajastecnicas/bajas/templates/bajas/acceso_denegado.html

{% extends "layout.html" %}
{% load static %}
{% block title %}
    Denegado 
{% endblock %}

{% block content %}
<div class="container text-center mt-5">
    <div class="alert alert-danger" role="alert">
        <h1 class="display-4">Acceso Denegado</h1>
        <p class="lead">Solo <strong>Ledesma</strong> puede </br> eliminar,editar o agregar registros.</p>
        <a href="{% url 'bajas:list' %}" class="btn btn-primary mt-3">Volver a la lista</a>
    </div>
</div>
{% endblock %}

bajastecnicas/bajas/templates/bajas/anexo2_template.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
        }
        th.primera { width: 4%; } 
        td.primera { width: 4%; }
        td {
            border: 1px solid #333;
            padding: 2px;
            text-align: left;
            width: 14%;
            height: 40px;
            
        }
        th {
            border: 1px solid #333;
            padding: 2px;
            text-align: left;
            width: 20%;
            height: 60px;
            background-color: #f2f2f2;
        }
       
         
    </style>
    <title>Anexo 2</title>
</head>
<body>
    <div style="text-align: right; font-size: 10px; margin-bottom: 10px;">
      Creado por: {{ usuario.username }}
    </div>
    <h2 style="text-align: center;">Anexo A 2, Resumen de medios propuestos para la baja (en Exel)</h2>
    <table>
        <thead>
            <tr>
                <th class="primera">No</th>
                <th>INVENTARIO </br> PARA AFT; </br>INMOVILIZADO</br> PARA</br> HERRAMIENTA</th>
                <th>DENOMINACIÓN </br>DEL MEDIO</br>SEGÚN SAP</th>
                <th>UNIDAD</br>ORGANIZATIVA,</br>ÁREA</br>SOLICITANTE</th>
                <th>MOTIVO DE BAJA:</br>OBSOLESCENCIA o </br>DETERIORO</th>
                <th>DESTINO</br>FINAL</br>PROPUESTO</th>
                <th>AÑOS DE USO;VALOR</br>RESIDUAL;MÁS</br>DETALLADO TÉCNICO</th>
            </tr>
        </thead>
        <tbody>
            {% for baja in bajas %}
            <tr>
                <td class="primera">{{ forloop.counter }}</td>
                <td>{{ baja.no_inv }}</td>
                <td>{{ baja.denominacion_SAP }}</td>
                <td>{{ baja.unidad_org }}</td>
                <td>{{ baja.motivo_baja }}</td>
                <td>{{ baja.destino_final }}</td>
                <td>{{ baja.años_explotacion }}/{{ baja.valor_residual }}/{{ baja.estado_actual }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="7">No hay bajas disponibles para Anexo 2.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

bajastecnicas/bajas/templates/bajas/anexo3_template.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
        }
        th.primera { width: 4%; } 
        td.primera { width: 4%; }
        td {
            border: 1px solid #333;
            padding: 2px;
            text-align: left;
            width: 20%;
            height: 40px;
            
        }
        th {
            border: 1px solid #333;
            padding: 2px;
            text-align: left;
            width: 14%;
            height: 60px;
            background-color: #f2f2f2;
        }
       
         
    </style>
    <title>Anexo 3</title>
</head>
<body>
    <div style="text-align: right; font-size: 10px; margin-bottom: 10px;">
      Creado por: {{ usuario.username }}
    </div>
    <h2 style="text-align: center;">No 4. ANEXO A3, ACTA DE LA COMISIÓN DE AUTORIZACION DE BAJAS TECNICAS</h2>
    <table>
        <thead>
            <tr>
                <th class="primera">No</th>                
                <th>No INVENTARIO</th>
                <th>DENOMINACIÓN DEL MEDIO</th>
                <th>UNIDAD ORGANIZATIVA</th>
                <th>MOTIVO DE BAJA</th>
                <th>DESTINO FINAL</th>
            </tr>
        </thead>
        <tbody>
            {% for baja in bajas %}
            <tr>
                <td class="primera">{{ forloop.counter }}</td>
                <td>{{ baja.no_inv }}</td>
                <td>{{ baja.denominacion_SAP }}</td>
                <td>{{ baja.unidad_org }}</td>
                <td>{{ baja.motivo_baja }}</td>
                <td>{{ baja.destino_final }}</td>
                {% comment %} <td>{{ baja.anios_explotacion }}/{{ baja.valor_residual }}/{{ baja.estado_actual }}</td> {% endcomment %}
            </tr>
            {% empty %}
            <tr>
                <td colspan="7">No hay bajas disponibles para Anexo 3.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

bajastecnicas/bajas/templates/bajas/anexo_0.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <title>Anexo A0</title>
    <style>
        body {
          font-family: Arial, sans-serif;
          font-size: 12px;
          text-align: center;
        }
        .title {
          font-size: 16px;
          font-weight: bold;
          margin-bottom: 10px;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 10px;
        }
        th,
        td {
          border: 1px solid black;
          padding: 5px;
          text-align: left;
        }
        .no-border {
          border: none;
        }
        .center {
          text-align: center;
        }
        .grey-background {
          background-color: #d3d3d3; /* Gris claro */
          text-align: center; /* Centramos el texto horizontalmente */
        }
        .background-gris-nocenter {
          background-color: #d3d3d3;
        }
  
        .row-with-four-columns td {
          width: 33%; /* Todas las celdas de 4 columnas ocupan el 33% */
        }
  
        td .titulo {
          width: 33%;
        }
        td .valor {
          width: 67%;
        }
        
        #tablausoactual td:empty::before {
            content: "\00a0";
        }
        #tabladestinofinal td:empty::before {
            content: "\00a0";
        }
        #tablafooter {
            table-layout: fixed;
            width: 100%;
            margin-top: 20px;
        }
        #tablafooter th, #tablafooter td {
            width: 33%;
            height: 40px;
            text-align: center;
        }
        #tablafooter td:empty::before {
            content: "\00a0";
        }
        .grey-background {
            background-color: #d3d3d3;
            text-align: center;
        }
      </style>
  </head>
  <body>
    <div style="text-align: right; font-size: 10px; margin-bottom: 10px;">
      Creado por: {{ usuario.username }}
    </div>
    <h2 class="title">ANEXO A0</h2>

    <!-- Primera tabla -->
    <table>
      <tr>
        <th class="no-border grey-background full-width" colspan="4">
          SOLICITUD DE DICTAMEN TÉCNICO
        </th>
      </tr>
      <tr>
        {% comment %}
        <td class="titulo">Unidad Organizativa</td>
        <td class="valor" colspan="3">{{ baja.unidad_org }}</td>
        {% endcomment %}
        <td>Unidad Organizativa</td>
        <td colspan="3">{{ baja.unidad_org }}</td>
      </tr>
      <tr>
        <td>Área a la que pertenece</td>
        <td colspan="3">{{ baja.area_pertenece }}</td>
      </tr>
      <tr class="row-with-four-columns">
        <td>Fecha</td>
        <td>{{ baja.date }}</td>
        <td>No. Solicitud</td>
        <td>{{ baja.no_solicitud }}</td>
        <!-- Por ahora en blanco -->
      </tr>
      <tr>
        <td>Fecha de creado en SAP</td>
        <td colspan="3">{{ baja.fecha_solicitud }}</td>
      </tr>
    </table>

    <!-- Segunda tabla -->
    <table>
      <tr>
        <td>EQUIPO/HERRAMIENTA</td>
        <td colspan="3">{{ baja.denominacion_SAP }}</td>
      </tr>
      <tr>
        <td>NÚMERO DE INVENTARIO</td>
        <td colspan="3">{{ baja.no_inv }}</td>
      </tr>
    </table>

    <!-- Tercera tabla -->
    <table>
      <tr>
        <td>Descripción del estado actual</td>
        <td colspan="3">{{ baja.estado_actual }}</td>
      </tr>
      <tr>
        <td colspan="4">{{ baja.descripcion_est_actual }}</td>
      </tr>
    </table>

    <!-- Cuarta tabla -->
    <table id="tablausoactual">
            <tr>
                <td class="background-gris-nocenter">Uso actual:</td>
            </tr>
            <tr>
                <td style="min-height: 40px;">
                    {{ baja.uso_actual|default:"&nbsp;"|safe }}
                </td>
            </tr>
    </table>

    <!-- Quinta tabla -->
    
    <table id="tabladestinofinal">
            <tr>
                <td class="background-gris-nocenter">Propuesta de destino final:</td>
            </tr>
            <tr>
                <td style="min-height: 40px;">
                    {{ baja.destino_final|default:"&nbsp;"|safe }}
                </td>
            </tr>
    </table>

    {% comment %} <table
      style="width: 100%; border-collapse: collapse"
      class="row-with-four-columns"
      colspan="4"
    > {% endcomment %}
    <table id="tablafooter">
      <thead>
        {% comment %} <tr class="grey-background full-width"> {% endcomment %}
        <tr class="grey-background">
          <th>Nombre</th>
          <th>Cargo</th>
          <th>Firma</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        
      </tbody>
    </table>
  </body>
</html>

bajastecnicas/bajas/templates/bajas/cargar_excel_inv.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Cargar Inventario{% endblock %}

{% block content %}
<div class="container mt-5">
  <h2 class="mb-4">Cargar archivo de inventario</h2>

 
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" id="msg-flash">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
      <label for="excel_file" class="form-label">Seleccionar archivo Excel</label>
      <input class="form-control" type="file" name="excel_file" id="excel_file" accept=".xlsx">
    </div>
    <button type="submit" class="btn btn-warning fw-bold text-dark">Cargar Inventario</button>
  </form>
</div>

<!-- Script para ocultar los mensajes luego de 5 segundos -->
<script>
  setTimeout(() => {
    const alert = document.getElementById("msg-flash");
    if (alert) {
      alert.classList.remove("show");
      alert.classList.add("hide");
    }
  }, 5000);
</script>
{% endblock %}

bajastecnicas/bajas/templates/bajas/editar_bajas.html
{% extends "layout.html" %}
{% block title %}
    Editar
{% endblock %} 
{% block content %}
<section class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="text-center">Editar Baja</h1> 
            {% comment %} {% if is_ledesma %}        {% endcomment %}
                {% comment %} <form action="{% url 'bajas:editar_baja' baja.id %}" method="post" enctype="multipart/form-data"> {% endcomment %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }} 
                    <button type="submit" class="btn btn-primary d-block mx-auto mt-4">Editar</button>
                    <a href="{% url 'bajas:list' %}" class="btn btn-secondary">Cancelar</a>
                </form>
            {% comment %} {% else %}
                <div class="col-12 text-center text-white mt-5 px-3" style="background-color: rgba(0, 0, 0, 0.5);">
                    <h2 class="display-4 font-weight-bold text-shadow">SOLO LEDESMA EDITA</h2>
                    
                </div>
            {% endif %}  {% endcomment %}
        </div>
    </div>
</section>
{% endblock %}

bajastecnicas/bajas/templates/bajas/error.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
    Error 
{% endblock %}
{% block content %}
    {{ mensaje }}
{% endblock %}