bajastecnicas/bajas/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'bajas'

urlpatterns = [
    path('', views.bajas_list, name="list"), 
    path('<int:id>', views.bajas_page, name="baja-page"), 
    path('crear-baja/', views.crear_baja, name="crear-baja"),
    path('crear-anexo2/', views.crear_anexo2, name="crear-anexo2"),
    path('crear-anexo3/', views.crear_anexo3, name="crear-anexo3"),
    path('<int:id>/eliminar', views.eliminar_baja, name='eliminar_baja'),
    path('<int:id>/editar', views.editar_baja, name='editar_baja'),                                 
    # path('<int:id>/exportar', views.exportar_pdf, name='exportar_pdf'), 
    path('<int:id>/subir_anexo/', views.subir_anexo_firmado, name='subir_anexo'),

    path('<int:id>/aprobar_anexoA/', views.aprobar_anexoA, name='aprobar_anexoA'),
    path('<int:id>/aprobar_anexoA1/', views.aprobar_anexoA1, name='aprobar_anexoA1'),
    path('<int:id>/aprobar_anexoA2/', views.aprobar_anexoA2, name='aprobar_anexoA2'),
    path('<int:id>/aprobar_anexoA3/', views.aprobar_anexoA3, name='aprobar_anexoA3'),
    
    # Para editar los datos del Anexo A
    
    
    # Ruta para el nuevo botón de crear el PDF del Anexo A (solo después de llenar los datos)
    path('<int:id>/crear_anexoA/', views.crear_anexoA, name='crear_anexoA'),
    path('<int:id>/crear_anexoA1/', views.crear_anexoA1, name='crear_anexoA1'),
    path('<int:id>/crear_anexoA2/', views.crear_anexoA2, name='crear_anexoA2'),
    path('<int:id>/crear_anexoA3/', views.crear_anexoA3, name='crear_anexoA3'),

    # Rutas para las versiones Anexo A1, A2, A3 si existen
    path('<int:id>/trabajar_anexoA/', views.trabajar_anexoA, name='trabajar_anexoA'),
    path('<int:id>/trabajar_anexoA1/', views.trabajar_anexoA1, name='trabajar_anexoA1'),
    path('<int:id>/trabajar_anexoA2/', views.trabajar_anexoA2, name='trabajar_anexoA2'),
    path('<int:id>/trabajar_anexoA3/', views.trabajar_anexoA3, name='trabajar_anexoA3'),

    path('cargar_excel_inv/', views.cargar_excel_inv, name='cargar_excel_inv'),    
    # Ruta para buscar inventarios
    path('buscar_inventario/', views.buscar_inventario, name='buscar_inventario'),  
    path('descargar_anexos/<int:id>/', views.descargar_anexos_zip, name='descargar_anexos'),                        
]

# Para servir archivos estáticos y de medios si estamos en modo DEBUG
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bajastecnicas/bajastecnicas/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('bajas/', include('bajas.urls')),
    path('users/', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bajastecnicas/users/urls.py
from django.urls import path
from . import views


app_name= 'users'

urlpatterns = [
    path('register/', views.register_view,name="register"), 
    path('login/', views.login_view,name="login"), 
    path('logout/', views.logout_view,name="logout"),  
    path("roles/", views.manage_roles_view, name="manage_roles"),
   
]

bajastecnicas/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Inicio
{% endblock %}

{% block content %}
<div class="container-fluid p-0">
    <!-- Fila de la imagen de fondo -->
    <div class="row vh-100 justify-content-center align-items-start" style="background-image: url('/static/bajastecnicas/icons/bajastecnicas.jpg'); background-size: cover; background-position: center;">
        <!-- Capa de superposición para el texto -->
        <div class="col-12 text-center text-white mt-5 px-3" style="background-color: rgba(0, 0, 0, 0.5);">
            <h2 class="display-4 font-weight-bold text-shadow">Gestor de</h2>
            <h1 class="display-1 font-weight-bold text-shadow">Bajas Técnicas</h1>
        </div>
    </div>
</div>
{% endblock %}

bajastecnicas/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" /> 
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />

    <style>
      body {
        background-color: #f8f9fa;
        color: #070743;
      }

      .navbar-custom {
        background-color: #070743;
      }

      .navbar-custom .navbar-brand,
      .navbar-custom .nav-link,
      .navbar-custom .btn,
      .navbar-custom .btn-logout {
        color: white !important;
      }

      .navbar-custom .nav-link:hover,
      .navbar-custom .navbar-brand:hover {
        color: #ffc107 !important;
      }

      .btn-logout {
        background-color: #ffc107;
        color: #070743;
        font-weight: bold;
        border: none;
      }

      .btn-logout:hover {
        background-color: #e0a800;
      }

      .btn-warning {
        color: #070743 !important;
        font-weight: bold;
      }

      .nav-item form {
        display: inline;
      }
      .dropdown-menu .dropdown-item:hover,
      .dropdown-menu .dropdown-item:focus {
        background-color: #0d6efd; /* azul bootstrap */
        color: #fff !important;    /* letras blancas */
      }
    </style>

    <title>{% block title %} Control Solicitudes{% endblock %}</title>
  </head>

  {% block scripts %} {% endblock %}
  <body>
    <nav class="navbar navbar-expand-lg navbar-custom">
      <div class="container">
        {% if user.is_authenticated %}
          <span class="nav-item">
            <span class="nav-link">Bienvenido: {{ user.username }}</span>
          </span>
        {% endif %}
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto">
            <li class="nav-item"><a class="nav-link" href="/">Inicio</a></li>
            {% if user.is_authenticated %}
              {% comment %} <li class="nav-item">
                <a class="nav-link" href="{% url 'bajas:list' %}">Solicitudes</a>
              </li> {% endcomment %}
              <li class="nav-item dropdown">
                <a 
                  class="nav-link dropdown-toggle" 
                  href="#" 
                  id="otrasSolicitudesDropdown" 
                  role="button" 
                  data-bs-toggle="dropdown" 
                  aria-expanded="false">
                  Solicitudes
                </a>
                <ul class="dropdown-menu" aria-labelledby="otrasSolicitudesDropdown">
                  <li>
                    <a class="dropdown-item" href="{% url 'bajas:list' %}">Todas</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'bajas:list' %}?rechazada=False&listopara_anexo_A2=True&listopara_anexo_A3=False">Solicitudes Anexo 2</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'bajas:list' %}?rechazada=False&listopara_anexo_A3=True&terminada=False">Solicitudes Anexo 3</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'bajas:list' %}?terminada=True">Solicitudes Terminadas</a>
                  </li>
                  <!-- Aquí podrás agregar más opciones en el futuro -->
                </ul>
              </li>
              <!-- Reemplazo de los links individuales por un dropdown -->
              <li class="nav-item dropdown">
                <a 
                  class="nav-link dropdown-toggle" 
                  href="#" 
                  id="otrasAccionesDropdown" 
                  role="button" 
                  data-bs-toggle="dropdown" 
                  aria-expanded="false">
                  Otras Acciones
                </a>
                <ul class="dropdown-menu" aria-labelledby="otrasAccionesDropdown">
                  <li>
                    <a class="dropdown-item" href="{% url 'bajas:crear-anexo2' %}">Crear PDF Anexo 2</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'bajas:crear-anexo3' %}">Crear PDF Anexo 3</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'bajas:crear-baja' %}">Crear Solicitud</a>
                  </li>
                  <!-- Aquí podrás agregar más opciones en el futuro -->
                </ul>
              </li>

              {% comment %} {% if user.username == 'ledesma' %} {% endcomment %}
              {% comment %} Anterior link "Crear Solicitud" removido y movido al dropdown {% endcomment %}
              {% comment %} {% endif %} {% endcomment %}
            {% else %}
              {% comment %} <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Registrarse</a>
              </li> {% endcomment %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Autenticarse</a>
              </li>
            {% endif %}
          </ul>

          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
              {% if puede_admin_roles %}
                <li class="nav-item">
                  <a class="btn btn-warning mx-2" href="{% url 'bajas:cargar_excel_inv' %}">
                    Cargar Excel Inventario
                  </a>
                </li>
              {% endif %}
              {% if puede_admin_roles %}
                <li class="nav-item">
                  <a class="btn btn-warning mx-2" href="{% url 'users:manage_roles' %}">
                    Administrar roles
                  </a>
                </li>
              {% endif %}
              <li class="nav-item">
                <form action="{% url 'users:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-logout">Logout</button>
                </form>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <main class="container mt-4">
      {% block content %} {% endblock %}
    </main>
  </body>
</html>